# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'be_in_touch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for be_in_touch

pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire', '~> 5.6.0'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
end
